[project]
name = "deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "gradio>=5.33.1",
    "isort>=6.0.1",
    "openai>=1.86.0",
    "openai-agents>=0.0.17",
]
